package pe.edu.contontinental.appdemopa3.view;

import pe.edu.contontinental.appdemopa3.service.DemoService;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/c/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware/
 */
public class DemoView extends javax.swing.JFrame {

	// Pasos u opciones
	// op = 1: Mostrar el menú
	// op = 2: Leer opcion de menú
	// op = 3: Opcion 1 del menu - Lee el Id del producto
	// op = 4: Opcion 2 del menu - Lee el Id del producto
	private int op;
	private String entrada;
	private int opMenu;
	private String menu, work;
	private DemoService service;
	private Long idProducto;
	private Long incremento;

	/**
	 * Creates new form SMEView
	 */
	public DemoView() {
		initComponents();
		this.setLocationRelativeTo(null);
		service = new DemoService();
		op = 1;
		entrada = "";
		proceso();
	}

	private void proceso() {
		String dato;
		Long id, stock;
		switch (op) {
			case 1:
				menu = "";
				menu += "MENU\n";
				menu += "=======================\n";
				menu += "1.- Consultar stock\n";
				menu += "2.- Actualizar stock\n";
				menu += "3.- Venta\n";
				menu += "4.- Salir\n";
				menu += "=======================\n";
				menu += "Opción? ";
				txtConsola.setText(menu);
				entrada = "";
				op = 2;
				break;
			case 2:
				opMenu = Integer.parseInt(entrada);
				dato = txtConsola.getText();
				if (opMenu < 1 || opMenu > 4) {
					dato += "\nOpción incorrecta.\n";
					dato += "Opción? ";
					txtConsola.setText(dato);
				} else {
					procesarMenu(opMenu);
				}
				entrada = "";
				break;
			case 3:
				id = Long.parseLong(entrada);
				stock = service.consultarStock(id);
				dato = txtConsola.getText();
				if (service.getCode() == 1) {
					dato += "\nStock: " + stock;
				} else {
					dato += "\nERROR: " + service.getMessage();
				}
				txtConsola.setText(dato);
				entrada = "";
				break;
			case 4:
				idProducto = Long.parseLong(entrada);
				dato = txtConsola.getText();
				dato += "\nIncremento: ";
				txtConsola.setText(dato);
				entrada = "";
				op = 5;
				break;
			case 5:
				incremento = Long.parseLong(entrada);
				stock = service.actualizarStock(idProducto, incremento);
				dato = txtConsola.getText();
				if (service.getCode() == 1) {
					dato += "\nNuevo stock: " + stock;
				} else {
					dato += "\nERROR: " + service.getMessage();
				}
				txtConsola.setText(dato);
				entrada = "";
				op = 1;
				break;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtConsola = new javax.swing.JTextArea();
      jPanel2 = new javax.swing.JPanel();
      btn0 = new javax.swing.JButton();
      btn1 = new javax.swing.JButton();
      btn2 = new javax.swing.JButton();
      btn3 = new javax.swing.JButton();
      btn4 = new javax.swing.JButton();
      btn5 = new javax.swing.JButton();
      btn6 = new javax.swing.JButton();
      btn7 = new javax.swing.JButton();
      btn8 = new javax.swing.JButton();
      btn9 = new javax.swing.JButton();
      btnEnter = new javax.swing.JButton();
      btnMenu = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("CAMBIA TU PLATA");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSOLA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N

      txtConsola.setEditable(false);
      txtConsola.setColumns(20);
      txtConsola.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
      txtConsola.setRows(5);
      jScrollPane1.setViewportView(txtConsola);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSOLA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N

      btn0.setBackground(new java.awt.Color(0, 51, 51));
      btn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn0.setForeground(new java.awt.Color(204, 255, 255));
      btn0.setText("0");
      btn0.setOpaque(false);
      btn0.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn0ActionPerformed(evt);
         }
      });

      btn1.setBackground(new java.awt.Color(0, 51, 51));
      btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn1.setForeground(new java.awt.Color(204, 255, 255));
      btn1.setText("1");
      btn1.setOpaque(false);
      btn1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn1ActionPerformed(evt);
         }
      });

      btn2.setBackground(new java.awt.Color(0, 51, 51));
      btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn2.setForeground(new java.awt.Color(204, 255, 255));
      btn2.setText("2");
      btn2.setOpaque(false);
      btn2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn2ActionPerformed(evt);
         }
      });

      btn3.setBackground(new java.awt.Color(0, 51, 51));
      btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn3.setForeground(new java.awt.Color(204, 255, 255));
      btn3.setText("3");
      btn3.setOpaque(false);
      btn3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn3ActionPerformed(evt);
         }
      });

      btn4.setBackground(new java.awt.Color(0, 51, 51));
      btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn4.setForeground(new java.awt.Color(204, 255, 255));
      btn4.setText("4");
      btn4.setOpaque(false);
      btn4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn4ActionPerformed(evt);
         }
      });

      btn5.setBackground(new java.awt.Color(0, 51, 51));
      btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn5.setForeground(new java.awt.Color(204, 255, 255));
      btn5.setText("5");
      btn5.setOpaque(false);
      btn5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn5ActionPerformed(evt);
         }
      });

      btn6.setBackground(new java.awt.Color(0, 51, 51));
      btn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn6.setForeground(new java.awt.Color(204, 255, 255));
      btn6.setText("6");
      btn6.setOpaque(false);
      btn6.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn6ActionPerformed(evt);
         }
      });

      btn7.setBackground(new java.awt.Color(0, 51, 51));
      btn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn7.setForeground(new java.awt.Color(204, 255, 255));
      btn7.setText("7");
      btn7.setOpaque(false);
      btn7.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn7ActionPerformed(evt);
         }
      });

      btn8.setBackground(new java.awt.Color(0, 51, 51));
      btn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn8.setForeground(new java.awt.Color(204, 255, 255));
      btn8.setText("8");
      btn8.setOpaque(false);
      btn8.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn8ActionPerformed(evt);
         }
      });

      btn9.setBackground(new java.awt.Color(0, 51, 51));
      btn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      btn9.setForeground(new java.awt.Color(204, 255, 255));
      btn9.setText("9");
      btn9.setOpaque(false);
      btn9.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn9ActionPerformed(evt);
         }
      });

      btnEnter.setBackground(new java.awt.Color(0, 51, 51));
      btnEnter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnEnter.setForeground(new java.awt.Color(204, 255, 255));
      btnEnter.setText("Enter");
      btnEnter.setOpaque(false);
      btnEnter.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEnterActionPerformed(evt);
         }
      });

      btnMenu.setBackground(new java.awt.Color(0, 51, 51));
      btnMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnMenu.setForeground(new java.awt.Color(204, 255, 255));
      btnMenu.setText("Menu");
      btnMenu.setOpaque(false);
      btnMenu.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnMenuActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(24, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(11, 11, 11)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(btnEnter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(11, 11, 11)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(8, 8, 8)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(13, 13, 13)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
		entrada += "0";
		txtConsola.setText(txtConsola.getText() + "0");
   }//GEN-LAST:event_btn0ActionPerformed

   private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
		entrada += "1";
		txtConsola.setText(txtConsola.getText() + "1");
   }//GEN-LAST:event_btn1ActionPerformed

   private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
		entrada += "2";
		txtConsola.setText(txtConsola.getText() + "2");
   }//GEN-LAST:event_btn2ActionPerformed

   private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
		entrada += "3";
		txtConsola.setText(txtConsola.getText() + "3");
   }//GEN-LAST:event_btn3ActionPerformed

   private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
		entrada += "4";
		txtConsola.setText(txtConsola.getText() + "4");
   }//GEN-LAST:event_btn4ActionPerformed

   private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
		entrada += "5";
		txtConsola.setText(txtConsola.getText() + "5");
   }//GEN-LAST:event_btn5ActionPerformed

   private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
		entrada += "6";
		txtConsola.setText(txtConsola.getText() + "6");
   }//GEN-LAST:event_btn6ActionPerformed

   private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
		entrada += "7";
		txtConsola.setText(txtConsola.getText() + "7");
   }//GEN-LAST:event_btn7ActionPerformed

   private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
		entrada += "8";
		txtConsola.setText(txtConsola.getText() + "8");
   }//GEN-LAST:event_btn8ActionPerformed

   private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
		entrada += "9";
		txtConsola.setText(txtConsola.getText() + "9");
   }//GEN-LAST:event_btn9ActionPerformed

   private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
		proceso();
   }//GEN-LAST:event_btnEnterActionPerformed

   private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
		op = 1;
		entrada = "";
		proceso();
   }//GEN-LAST:event_btnMenuActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DemoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DemoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DemoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DemoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DemoView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn0;
   private javax.swing.JButton btn1;
   private javax.swing.JButton btn2;
   private javax.swing.JButton btn3;
   private javax.swing.JButton btn4;
   private javax.swing.JButton btn5;
   private javax.swing.JButton btn6;
   private javax.swing.JButton btn7;
   private javax.swing.JButton btn8;
   private javax.swing.JButton btn9;
   private javax.swing.JButton btnEnter;
   private javax.swing.JButton btnMenu;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea txtConsola;
   // End of variables declaration//GEN-END:variables

	private void procesarMenu(int opMenu) {
		switch (opMenu) {
			case 1:
				work = "CONSULTA DE STOCK \n";
				work += "================== \n\n";
				work += "Id de producto? ";
				txtConsola.setText(work);
				entrada = "";
				op = 3;
				break;
			case 2:
				work = "ACTUALIZAR STOCK\n";
				work += "================== \n\n";
				work += "Id de producto? ";
				txtConsola.setText(work);
				entrada = "";
				op = 4;
				break;
		}

	}

}
