package pe.uni.eurekaapp.view;

import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFDataFormat;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import pe.uni.eurekaapp.controller.CuentaController;
import pe.uni.eurekaapp.util.Mensaje;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/c/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware/
 */
public class ConsultaMovimientos extends javax.swing.JInternalFrame {

	private List<Map<String, ?>> lista = null;
	
	/**
	 * Creates new form ConsultaMovimientos
	 */
	public ConsultaMovimientos() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtCuenta = new javax.swing.JTextField();
      btnExcel = new javax.swing.JButton();
      btnConsultar = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblResultado = new javax.swing.JTable();

      setClosable(true);
      setMaximizable(true);
      setTitle("CONSULTA DE MOVIMIENTOS");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTROL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jLabel1.setText("Cuenta");

      txtCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

      btnExcel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnExcel.setText("Excel");
      btnExcel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnExcelActionPerformed(evt);
         }
      });

      btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      btnConsultar.setText("Consultar");
      btnConsultar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConsultarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(225, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
               .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(23, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N

      tblResultado.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "CUENTA", "MOVIMIENTO", "FECHA", "IMPORTE"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, true, true
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      jScrollPane1.setViewportView(tblResultado);
      if (tblResultado.getColumnModel().getColumnCount() > 0) {
         tblResultado.getColumnModel().getColumn(0).setResizable(false);
         tblResultado.getColumnModel().getColumn(1).setResizable(false);
         tblResultado.getColumnModel().getColumn(2).setResizable(false);
         tblResultado.getColumnModel().getColumn(3).setResizable(false);
      }

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
		try {
			// Datos
			String cuenta = txtCuenta.getText();
			// Proceso
			CuentaController control = new CuentaController();
			lista = control.getMovimientos(cuenta);
			// Mostrar resultado
			DefaultTableModel tabla;
			tabla = (DefaultTableModel) tblResultado.getModel();
			tabla.setRowCount(0);
			for (Map<String, ?> r : lista) {
				Object[] rowData = {
					r.get("CUENCODIGO").toString(),
					r.get("TIPONOMBRE").toString(),
					r.get("MOVIFECHA").toString(),
					Double.parseDouble(r.get("MOVIIMPORTE").toString())
				};
				tabla.addRow(rowData);
			}
		} catch (Exception e) {
			Mensaje.error(this, e.getMessage());
		}
   }//GEN-LAST:event_btnConsultarActionPerformed

   private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
		try {
			// Creación del libro
			String plantilla = "/pe/uni/eurekaapp/plantillas/MOVIMIENTOS.xls";
			InputStream isPlantilla = Class.class.getResourceAsStream(plantilla);
			POIFSFileSystem fs = new POIFSFileSystem(isPlantilla);
			HSSFWorkbook objLibro = new HSSFWorkbook(fs, true);
			// Crea la hoja
			HSSFSheet hoja = objLibro.getSheetAt(0);
			// Cargar los datos a la hoja
			int numFila = 1;
			HSSFRow objFila;
			for (Map<String, ?> map : lista) {
				numFila++;
				objFila = hoja.createRow(numFila);
				crearCeldaCadena(objFila, 0, map.get("CUENCODIGO").toString());
				crearCeldaEntera(objFila, 1, Integer.parseInt(map.get("MOVINUMERO").toString()));
				crearCeldaCadena(objFila, 2, map.get("MOVIFECHA").toString());
				crearCeldaCadena(objFila, 3, map.get("TIPONOMBRE").toString());
				crearCeldaDecimal(objFila, 4, Double.parseDouble(map.get("MOVIIMPORTE").toString()));
			}
			// Se vuelca la información a un archivo.
			FileOutputStream fileOut = new FileOutputStream("E://MOVIMIENTOS.xls");
			objLibro.write(fileOut);
			fileOut.close();
			System.out.println("Todo ok.");
		} catch (Exception e) {
			e.printStackTrace();
		}
   }//GEN-LAST:event_btnExcelActionPerformed

	private void crearCeldaCadena(HSSFRow fila, int columna, String dato) {
		HSSFCell celda = fila.createCell(columna, HSSFCell.CELL_TYPE_STRING);
		celda.setCellValue(dato);
	}

	private void crearCeldaEntera(HSSFRow fila, int columna, int dato) {
		HSSFCell celda = fila.createCell(columna, HSSFCell.CELL_TYPE_NUMERIC);
		HSSFCellStyle style = fila.getSheet().getWorkbook().createCellStyle();
		style.setDataFormat(HSSFDataFormat.getBuiltinFormat("0"));
		celda.setCellStyle(style);
		celda.setCellValue(dato);
	}

	private void crearCeldaDecimal(HSSFRow fila, int columna, double dato) {
		HSSFCell celda = fila.createCell(columna, HSSFCell.CELL_TYPE_NUMERIC);
		HSSFCellStyle style = fila.getSheet().getWorkbook().createCellStyle();
		style.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0.00"));
		celda.setCellStyle(style);
		celda.setCellValue(dato);
	}
	

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnConsultar;
   private javax.swing.JButton btnExcel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblResultado;
   private javax.swing.JTextField txtCuenta;
   // End of variables declaration//GEN-END:variables

}
