/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.uni.practica03.view;

import javax.swing.JOptionPane;
import pe.edu.uni.practica03.dto.PagoDto;
import pe.edu.uni.practica03.service.Practica03Service;

/**
 *
 * @author Natsumi Aileen
 */
public class Practica03View extends javax.swing.JFrame {

	/**
	 * Creates new form Practica03View
	 */
	public Practica03View() {
		initComponents();
		this.setLocationRelativeTo(null);
		txtHoras.requestFocus();
		establecerContador();
	}
	
	private void establecerContador(){
		String titulo = "Trabajador nro. " + Comunes.getSiguiente();
		lblTitulo.setText(titulo);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      txtHoras = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      txtPagoHoras = new javax.swing.JTextField();
      txtDias = new javax.swing.JTextField();
      lblTitulo = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      btnProcesar = new javax.swing.JButton();
      btnNuevo = new javax.swing.JButton();
      btnSalir = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      txtSalario = new javax.swing.JTextField();
      txtRenta = new javax.swing.JTextField();
      txtTotal = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jLabel1.setText("EMPRESA VIA EXITOS");

      txtHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel2.setText("Horas Trabajadas");

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel3.setText("Dias Trabajados");

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel4.setText("Pago x Hora");

      txtPagoHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      txtPagoHoras.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtPagoHorasKeyPressed(evt);
         }
      });

      txtDias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      lblTitulo.setForeground(new java.awt.Color(0, 102, 255));
      lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblTitulo.setText("Horas Trabajadas");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(txtPagoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel2)
                  .addGap(51, 51, 51)
                  .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(31, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtPagoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

      btnProcesar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnProcesar.setText("Procesar");
      btnProcesar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnProcesarActionPerformed(evt);
         }
      });

      btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnNuevo.setText("Nuevo");
      btnNuevo.setEnabled(false);
      btnNuevo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNuevoActionPerformed(evt);
         }
      });

      btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      btnSalir.setText("Salir");
      btnSalir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalirActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
               .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(btnProcesar)
            .addGap(18, 18, 18)
            .addComponent(btnNuevo)
            .addGap(18, 18, 18)
            .addComponent(btnSalir)
            .addContainerGap(32, Short.MAX_VALUE))
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

      jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel5.setText("Salario");

      jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel6.setText("Imp. Renta (8%)");

      jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
      jLabel7.setText("Total");

      txtSalario.setEditable(false);
      txtSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      txtRenta.setEditable(false);
      txtRenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      txtTotal.setEditable(false);
      txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel5)
               .addComponent(jLabel6)
               .addComponent(jLabel7))
            .addGap(44, 44, 44)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(133, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(19, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(173, 173, 173)
                  .addComponent(jLabel1))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(33, 33, 33)
                  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGap(42, 42, 42))
         .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
		 try {
			 Comunes.validarCajaTexto(txtHoras, "Ingrese la cantidad de Horas trabajadas por Dia.");
			 Comunes.validarCajaTexto(txtDias, "Ingrese la cantidad de Dias trabajados.");
			 Comunes.validarCajaTexto(txtPagoHoras, "Ingrese el Pago por Horas.");
			 Comunes.validarEntero(txtHoras, "Ingrese horas correctas.");
			 Comunes.validarEntero(txtDias, "Ingrese dias correctas.");
			 Comunes.validarDecimal(txtPagoHoras, "Ingrese pago correcto.");
			 procesarDatos();
		 } catch (Exception e) {
			 JOptionPane.showMessageDialog(this, e.getMessage());
		 }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

		 txtPagoHoras.setText("");
		 txtHoras.setText("");
		 txtDias.setText("");
		 txtSalario.setText("");
		 txtRenta.setText("");
		 txtTotal.setText("");

		 btnNuevo.setEnabled(false);
		 btnProcesar.setEnabled(true);
		 txtHoras.requestFocus();

		 establecerContador();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

		 System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtPagoHorasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoHorasKeyPressed
/*
		 if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			 if (txtHoras.getText().equals("")) {
				 JOptionPane.showMessageDialog(null, "Ingrese la cantidad de Horas trabajadas por Dia");
				 txtHoras.requestFocus();
			 } else if (txtDias.getText().equals("")) {
				 JOptionPane.showMessageDialog(null, "Ingrese la cantidad de Dias trabajados");
				 txtDias.requestFocus();
			 } else if (txtPagoHoras.getText().equals("")) {
				 JOptionPane.showMessageDialog(null, "Ingrese el Pago por Horas");
				 txtPagoHoras.requestFocus();
			 } else {
				 if (Comunes.isNumeric(txtHoras.getText()) == false) {
					 JOptionPane.showMessageDialog(null, "Ingrese Datos Validos");
					 txtHoras.setText("");
					 txtHoras.requestFocus();
				 } else if (Comunes.isNumeric(txtDias.getText()) == false) {
					 JOptionPane.showMessageDialog(null, "Ingrese Datos Validos");
					 txtDias.setText("");
					 txtDias.requestFocus();
				 } else if (Comunes.isDecimal(txtPagoHoras.getText()) == false) {
					 JOptionPane.showMessageDialog(null, "Ingrese Datos Validos");
					 txtPagoHoras.setText("");
					 txtPagoHoras.requestFocus();
				 } else {
					 ProcesarDatos();
				 }
			 }
		 }
*/
    }//GEN-LAST:event_txtPagoHorasKeyPressed

	public void procesarDatos() {
		// Variables
		int horas, dias;
		double pagoxhoras;
		PagoDto dto = new PagoDto();
		// Datos
		horas = Integer.parseInt(txtHoras.getText());
		dias = Integer.parseInt(txtDias.getText());
		pagoxhoras = Double.parseDouble(txtPagoHoras.getText());
		dto.setHorasDia(horas);
		dto.setDias(dias);
		dto.setPagoHora(pagoxhoras);
		// Proceso
		Practica03Service service = new Practica03Service();
		dto = service.procSalario(dto);
		// Reporte
		txtSalario.setText("S/. " + Comunes.formato(dto.getIngreso()));
		txtRenta.setText("S/. " + Comunes.formato(dto.getRenta()));
		txtTotal.setText("S/. " + Comunes.formato(dto.getNeto()));

		btnNuevo.setEnabled(true);
		btnProcesar.setEnabled(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Practica03View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Practica03View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Practica03View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Practica03View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Practica03View().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnNuevo;
   private javax.swing.JButton btnProcesar;
   private javax.swing.JButton btnSalir;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JLabel lblTitulo;
   private javax.swing.JTextField txtDias;
   private javax.swing.JTextField txtHoras;
   private javax.swing.JTextField txtPagoHoras;
   private javax.swing.JTextField txtRenta;
   private javax.swing.JTextField txtSalario;
   private javax.swing.JTextField txtTotal;
   // End of variables declaration//GEN-END:variables
}
